package de.stefanet.javachesskit.bitboard;

public enum Status {
	VALID,
	NO_WHITE_KING,
	NO_BLACK_KING,
	TOO_MANY_KINGS,
	TOO_MANY_WHITE_PAWNS,
	TOO_MANY_BLACK_PAWNS,
	PAWNS_ON_BACKRANK,
	TOO_MANY_WHITE_PIECES,
	TOO_MANY_BLACK_PIECES,
	BAD_CASTLING_RIGHTS,
	INVALID_EP_SQUARE,
	OPPOSITE_CHECK,
	EMPTY,
	TOO_MANY_CHECKERS,
	IMPOSSIBLE_CHECK;
}
